// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzxbtcrlxyfgshqjuelt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6eGJ0Y3JseHlmZ3NocWp1ZWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzI4MjQsImV4cCI6MjA2OTY0ODgyNH0.8CB_0qF_bzPKxTHXD9HpTSUsXKueQhE_T1thCCk2CVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});